apiVersion: v1
kind: Namespace
metadata:
  name: traffic
  labels:
    app: traffic
    istio-injection: enabled

---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: traffic
  namespace: traffic
automountServiceAccountToken: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic
  namespace: traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic
  template:
    metadata:
      labels:
        app: traffic
    spec:
      serviceAccountName: traffic
      containers:
      - name: curl
        image: curlimages/curl:8.5.0
        command: ["/bin/sh", "-c", "--"]
        args: ["while true; do curl -m 2 -I http://web.web.svc.cluster.local 2> /dev/null; sleep 2; done;"]
