apiVersion: v1
kind: Namespace
metadata:
  name: traffic
  labels:
    app: traffic
    istio-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic
  namespace: traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic
  template:
    metadata:
      labels:
        app: traffic
    spec:
      containers:
      - name: curl
        image: curlimages/curl:8.5.0
        command: ["/bin/sh", "-c", "--"]
        args: ["while true; do curl -I http://web.web 2> /dev/null; sleep 3; done;"]
