service:
  type: NodePort
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
    nodePort: 30000
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 30002
autoscaling:
  enabled: false
nodeSelector:
  istio-ingress: "true"
