---
pilot:
  autoscaleEnabled: false
  seccompProfile:
    type: RuntimeDefault
  replicaCount: 1
  podAnnotations:
    prometheus.io/port: "15014"
    prometheus.io/scrape: "true"
  nodeSelector:
    istio-controlplane: "true"
  env:
    PILOT_ENABLE_AMBIENT: "true"
meshConfig:
  enablePrometheusMerge: true
  accessLogFile: /dev/stdout
  accessLogEncoding: 'JSON'
  accessLogFormat: |
    {
      "time": "%EMIT_TIME%",
      "start_time": "%START_TIME%",
      "method": "%REQ(:METHOD)%",
      "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
      "downstream_protocol": "%PROTOCOL%",
      "response_code": "%RESPONSE_CODE%",
      "response_flags": "%RESPONSE_FLAGS%",
      "response_code_details": "%RESPONSE_CODE_DETAILS%",
      "connection_termination_details": "%CONNECTION_TERMINATION_DETAILS%",
      "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
      "bytes_received": "%BYTES_RECEIVED%",
      "bytes_sent": "%BYTES_SENT%",
      "duration": "%DURATION%",
      "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
      "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
      "user_agent": "%REQ(USER-AGENT)%",
      "request_id": "%REQ(X-REQUEST-ID)%",
      "authority": "%REQ(:AUTHORITY)%",
      "upstream_remote_address": "%UPSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%",
      "upstream_remote_port": "%UPSTREAM_REMOTE_PORT%",
      "upstream_cluster": "%UPSTREAM_CLUSTER%",
      "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%",
      "upstream_local_port": "%UPSTREAM_LOCAL_PORT%",
      "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%",
      "downstream_local_port": "%DOWNSTREAM_LOCAL_PORT%",
      "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%",
      "downstream_remote_port": "%DOWNSTREAM_REMOTE_PORT%",
      "requested_server_name": "%REQUESTED_SERVER_NAME%",
      "route_name": "%ROUTE_NAME%",
      "upsteam_protocol": "%UPSTREAM_PROTOCOL%",
      "upstream_request_attempt_count": "%UPSTREAM_REQUEST_ATTEMPT_COUNT%",
      "response_duration": "%RESPONSE_DURATION%",
      "downstream_tls_version": "%DOWNSTREAM_TLS_VERSION%",
      "downstream_connection_id": "%CONNECTION_ID%",
      "hostname": "%HOSTNAME%",
      "upstream_tls_version": "%UPSTREAM_TLS_VERSION%"
    }
  defaultConfig:
    proxyMetadata:
      ISTIO_META_ENABLE_HBONE: "true"
